title: Arty06
theme: PaperMod
baseURL: "https://artyeth06.github.io/"

paginate: 5
enableInlineShortcodes: true
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true

minify:
  disableXML: true

outputs:
  home:
    - HTML
    - JSON

menu:
  main:
    - name: Cheat sheet
      url: categories/cheat-sheet
      weight: 1
    - name: Tags
      url: tags/
      weight: 2
    - name: Search
      url: search/
      weight: 3
    - name: About
      url: about/
      weight: 4

params:
  env: production
  description: "Blog about cybersecurity, CTF."
  keywords: [blog, cybersecurity, ctf, hacking, it, tech]
  defaultTheme: dark
  disableThemeToggle: true
  disableSpecial1stPost: true
  ShowCodeCopyButtons: true
  ShowToc: true

  mainSections:
    - posts

  profileMode:
    enabled: true
    title: Arty06
    imageUrl: "avatar.png"
    imageTitle: "Arty06"
    imageWidth: 120
    imageHeight: 120
    subtitle: "HighSchool student | Cybersecurity enthusiast"

  socialIcons:
    - name: codepen
      url: "https://codepen.io/ArtyETH06"
    - name: github
      url: "https://github.com/ArtyETH06"
    - name: rootme
      url: "https://www.root-me.org/Arty06"

  label:
    text: "Arty06"
    icon: "avatar.png"
    iconHeight: 30
  
  assets:
    favicon: "favicons/favicon.ico"
    favicon16x16:  "favicons/favicon-16x16.png"
    favicon32x32:  "favicons/favicon-32x32.png"
    apple_touch_icon:  "favicons/apple-touch-icon.png"
    safari_pinned_tab:  "favicons/favicon.ico"

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

markup:
  goldmark:
    renderer:
      unsafe: true
